package com.f2d.chatroom.domain;

public class AppConstants {
    public static final String GET_ALL_CHAT_GROUPS_SUCCESS_MSG = "GET ALL CHAT GROUP INFORMATION SUCCESS";
    public static final String GET_ALL_CHAT_GROUPS_FAILURE_MSG = "GET ALL CHAT GROUP INFORMATION FAILURE";
    public static final String GET_CHAT_GROUP_BY_ID_SUCCESS_MSG = "GET CHAT GROUP BY ID SUCCESS";
    public static final String GET_CHAT_GROUP_BY_ID_FAILURE_MSG = "GET CHAT GROUP BY ID FAILURE";
    public static final String CREATE_CHAT_GROUP_SUCCESS_MSG = "CREATE CHAT GROUP SUCCESS";
    public static final String CREATE_CHART_GROUP_FAILURE_MSG = "CREATE CHAT GROUP FAILURE";
    public static final String UPDATE_CHAT_GROUP_SUCCESS_MSG = "UPDATE CHAT GROUP SUCCES";
    public static final String UPDATE_CHAT_GROUP_FAILURE_MSG = "UPDATE CHAT GROUP FAILURE";
    public static final String DELETE_CHAT_GROUP_SUCCESS_MSG = "DELETE CHAT GROUP SUCCESS";
    public static final String DELETE_CHAT_GROUP_FAILURE_MSG = "DELETE CHAT GROUP FAILURE";
    public static final String GET_ALL_CHAT_MESSAGES_SUCCESS_MSG = "GET ALL CHAT MESSAGES SUCCESS";
    public static final String GET_ALL_CHAT_MESSAGES_FAILURE_MSG = "GET ALL CHAT MESSAGES FAILURE";
    public static final String GET_CHAT_MESSAGE_BY_ID_SUCCESS_MSG = "GET CHAT MESSAGE BY ID SUCCESS";
    public static final String GET_CHAT_MESSAGE_BY_ID_FAILURE_MSG = "GET CHAT MESSAGE BY ID FAILURE";
    public static final String CREATE_UPDATE_CHAT_MESSAGE_SUCCESS_MSG = "CREATE/UPDATE CHAT MESSAGE SUCCESS";
    public static final String CREATE_UPDATE_CHAT_MESSAGE_FAILURE_MSG = "CREATE/UPDATE CHAT MESSAGE FAILURE";
    public static final String DELETE_CHAT_MESSAGE_SUCCESS_MSG = "DELETE CHAT MESSAGE SUCCESS";
    public static final String DELETE_CHAT_MESSAGE_FAILURE_MSG = "DELETE CHAT MESSAGE FAILURE";
}
